#Project Details
site_name: Gluu Documentation
site_description: Documentation for Gluu software products

# copyright
copyright: Copyright &copy; 2018, Gluu, Inc.

# configuration
docs_dir: source
repo_name: GluuFederation/docs
repo_url: https://github.com/GluuFederation/docs
edit_uri: edit/master/source

# Theme
theme: 
    name: material
    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
    
# extensions    
markdown_extensions:
- admonition
- toc:
     permalink: '#'
     
# Navigation
nav:
- Products: 'index.md'

