site_name: Gluu Documentation
site_description: Documenation for Gluu Server
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-home
theme_dir: material
extra:
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Products: 'index.md'
#- Access Management: 'gluucehome.md'
#- oxd: 'oxdhome.md'