site_name: Gluu Documentation
site_description: Documentation for Gluu software products
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2018, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-home
theme_dir: material
extra:
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Products: 'index.md'

