# Project information
site_name: Cluster Manager 4.3 Docs
site_description: Documentation for Gluu Cluster Manager

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-clustermgr-prod
repo_url: https://github.com/GluuFederation/docs-clustermgr-prod/
edit_uri: edit/4.3/docs/source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '4.3'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '4.3': 'https://gluu.org/docs/cm/4.3/'
    - '4.2': 'https://gluu.org/docs/cm/4.2/'
    - '4.1': 'https://gluu.org/docs/cm/4.1/'
    - '4.0': 'https://gluu.org/docs/cm/4.0/'
    - 'EOL Versions': 'https://gluu.org/docs/eol'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- Home: 'index.md'
- Architecture: 'architecture/index.md'
- Install: 'installation/index.md'
- Deploy Clusters: 'deploy/index.md'
- Configure AWS Load Balancer: 'aws-config/index.md'
- Operation Guide:
    - 'Upgrades': 'operations/upgrade.md'  
    - 'Backups': 'operations/backup.md'  
- Troubleshooting: 'troubleshooting/index.md'
